name: "Sentinel Format (fmt)"
description: 'This action uses the `sentinel fmt` command to check that all sentinel files are in the canonical format.'
author: 'Benoit Blais'

inputs:
  check:
    description: 'By default, fmt checks if the input is properly formatted. If you set it to false, code will be formated in a canonical format.'
    required: false
    default: true
    type: bool
  version:
    description: "Sentinel version to install."
    required: false
    default: latest
    type: string
  working_dir:
    description: "Sentinel working directory."
    required: false
    default: "."
    type: string
  subdirectories:
    description: "Whether or not to search for Sentinel files inside subdirectories."
    required: false
    default: true
    type: bool
  comment:
    description: "Whether or not to comment on pull request."
    required: false
    default: true
    type: bool
  delete_comment:
    description: "Whether or not to delete previous comment on pull request."
    required: false
    default: true
    type: bool

outputs:
  exitcode:
    description: 'The exit code of the Sentinel fmt command.'
    value: ${{ steps.bashscript.outputs.exitcode }}

runs:
  using: "composite"
  steps:
    - id: bashscript
      shell: bash
      run: bash ${{ github.action_path }}/main.sh
      env:
        INPUT_CHECK: ${{ inputs.check }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_WORKING_DIR: ${{ inputs.working_dir }}
        INPUT_SUBDIRECTORIES: ${{ inputs.subdirectories }}
        INPUT_COMMENT: ${{ inputs.comment }}
        INPUT_DELETE_COMMENT: ${{ inputs.delete_comment }}
