name: "Sentinel GitHub Actions"
description: "Runs Sentinel commands via GitHub Actions."
author: 'Benoit Blais'

inputs:
  command:
    description: "Sentinel command to execute."
    required: true
  version:
    description: "Sentinel version to install."
    default: latest
  comment:
    description: "Whether or not to comment on pull requests."
    default: true
  working_dir:
    description: "Sentinel working directory."
    default: "."

outputs:
  output:
    description: "The Sentinel outputs."

runs:
  using: "composite"
  steps:
    - id: bashscript
      shell: bash
      run: bash ${{ github.action_path }}/main.sh
      env:
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_COMMENT: ${{ inputs.comment }}
        INPUT_WORKING_DIR: ${{ inputs.working_dir }}