name: "Sentinel GitHub Actions"
description: "Runs Sentinel commands via GitHub Actions."
author: 'Benoit Blais'

inputs:
  stl_actions_subcommand:
    description: "Sentinel subcommand to execute."
    required: true
  stl_actions_version:
    description: "Sentinel version to install."
    required: true
  stl_actions_comment:
    description: "Whether or not to comment on pull requests."
    default: true
  stl_actions_working_dir:
    description: "Sentinel working directory."
    default: "."

outputs:
  stl_actions_output:
    description: "The Sentinel outputs."

runs:
  using: "composite"
  steps:
    - id: bashscript
      shell: bash
      run: bash ${{ github.action_path }}/main.sh
      env:
        INPUT_STL_ACTIONS_SUBCOMMAND: ${{ inputs.stl_actions_subcommand }}
        INPUT_STL_ACTIONS_VERSION: ${{ inputs.stl_actions_version }}
        INPUT_STL_ACTIONS_COMMENT: ${{ inputs.stl_actions_comment }}
        INPUT_STL_ACTIONS_WORKING_DIR: ${{ inputs.stl_actions_working_dir }}